const constants = {
  HTTP_CODE_400_MESSAGE: "Bad Request",
  HTTP_CODE_400_CODE: "400",
  HTTP_CODE_403_MESSAGE: "Forbidden",
  HTTP_CODE_403_CODE: "403",
  HTTP_CODE_404_MESSAGE: "Not Found",
  HTTP_CODE_404_CODE: "404",
  HTTP_CODE_401_MESSAGE: "Unauthorized",
  HTTP_CODE_401_CODE: "401",
  HTTP_CODE_422_MESSAGE: "Unprocessable Entity",
  HTTP_CODE_422_CODE: "422",
  HTTP_CODE_500_MESSAGE: "Internal Server Error",
  HTTP_CODE_500_CODE: "500",
  HTTP_CODE_429_MESSAGE: "Too Many Requests",
  HTTP_CODE_429_CODE: "429",
  CATEGORY_LIMIT_REACHED_MESSAGE: "Category Limit Reached",
  CATEGORY_LIMIT_REACHED_CODE: "429",
  TAG_LIMIT_REACHED_MESSAGE: "Tag Limit Reached",
  TAG_LIMIT_REACHED_CODE: "429",
  SLUG_NOT_UNIQUE_MESSAGE: "Slug not unique",
  DOMAIN_NOT_UNIQUE_MESSAGE: "Domain not unique",
  SITE_PREFIX_NOT_UNIQUE_MESSAGE: "Site prefix not unique",
  CUSTOM_DOMAIN_NOT_ALLOWED: "Custom domain not allowed",
  REDEEM_SUCCESSFULLY: "License key redeemed successfully!",
  DETACHED_SUCCESSFULLY: "License key detached successfully!",
  LICENSE_ALREADY_EXISTS_IN_SITE: "License key already exists in this site!",
  LICENSE_NOT_VALID: "License key is not valid!",
};

export { constants };
